version: "3.9"
services:
  web-app:
    depends_on:
      - rabbitmq
      - data-app
    build: ./web-app
    ports:
      - "3000:3000"

  data-app:
    depends_on:
      - rabbitmq
      - mysql
    build: ./data-app

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
        - ./data-app/init.sql:/data/application/init.sql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ingestion_job_db