version: "3.9"
services:
  web-app:
    depends_on:
      - rabbitmq
      - data-app
    build: ./web-app
    ports:
      - "3000:3000"

  data-app:
    depends_on:
      - rabbitmq
      - mysql
    build: ./data-app
  
  nginx:
    depends_on:
      - web-app
    image: nginx
    ports:
      - "80:80"
      - "443:443"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root